@api_HostAddress = https://localhost:7029

GET {{api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{api_HostAddress}}/weatherforecast

###

GET {{api_HostAddress}}/weatherforecast

###
